version: "3.9"

volumes:
  redis-data: {}

services:
  redis:
    image: redis:7-alpine
    container_name: next-media-redis
    ports:
      - "6000:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: next-media-web
    ports:
      - "5173:80"